name: zc_agentbeacon_hub
description: ZcAgentBeacon dashboard Hub implementation.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  zc_agentbeacon_core:
    path: ../../packages/zc_agentbeacon_core

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
